#!/bin/bash
# Base on:  yeho <lj2007331 AT gmail.com>
# BLOG:  https://linuxeye.com

echo=echo

# --- Reset ---
CEND="\033[0m"

# --- Colores de texto ---
CBLACK="\033[0;30m"
CRED="\033[1;31m"
CGREEN="\033[1;32m"
CYELLOW="\033[1;33m"
CBLUE="\033[1;34m"
CMAGENTA="\033[1;35m"
CCYAN="\033[1;36m"
CWHITE="\033[1;37m"

# --- Fondos ---
BRED="\033[41m"
BGREEN="\033[42m"
BYELLOW="\033[43m"
BBLUE="\033[44m"
BMAGENTA="\033[45m"
BCYAN="\033[46m"
BWHITE="\033[47m"
BGRAY="\033[100m"

# --- Estilos de mensajes ---
CSUCCESS="${CGREEN}[✔]${CEND}"
CERROR="${CRED}[✖]${CEND}"
CWARNING="${CYELLOW}[!]${CEND}"
CINFO="${CBLUE}[i]${CEND}"

# --- Encabezados y secciones ---
CHEADER="${BBLUE}${CWHITE}"
CSECTION="${BGRAY}${CWHITE}"
CNOTICE="${BYELLOW}${CBLACK}"

# --- Funciones rápidas ---
header() {
    echo -e "\n${CHEADER} $1 ${CEND}\n"
}

section() {
    echo -e "\n${CSECTION} $1 ${CEND}\n"
}

notice() {
    echo -e "\n${CNOTICE} $1 ${CEND}\n"
}
